[log]
    stdout = true

[memcacheSlots]
    # slot hash规则:
    # mod(target, n): 对target模n
    # substr(key[,start[,stop]]): 截取字符串key[start, top)
    # eg: mod(key, 5)
    # eg: mod(substr(key, -4, -2), 8)
    hashExpr = "mod(key, 4)"
	# 是否zlib压缩
	#zlib = true
	#db = 23
	addrs = ["1.1.1.1", "1.1.1.2", "1.1.1.3", "1.1.1.4"]
    [memcacheSlots.memcache]
        # pool
        active = 10
        idle   = 10

        # basic
        name   = "lushancluster"
        proto  = "tcp"
        dialTimeout  = "5s"
        readTimeout  = "5s"
        writeTimeout = "5s"
        idleTimeout  = "80s"


